In [1]:
import pandas as pd

In [3]:
import os

os.getcwd()

'C:\\Users\\avnia'

In [4]:
os.listdir()

['.anaconda',
 '.bito',
 '.bitowingman',
 '.codex',
 '.conda',
 '.continuum',
 '.copilot',
 '.gitconfig',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.vscode',
 '.vscode-shared',
 'anaconda_projects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'CrossDevice',
 'Customer shopping behavior analysis .ipynb',
 'customer_behavior_analysis.ipynb',
 'customer_shopping_behaviour_analysis.csv',
 'Documents',
 'Downloads',
 'Favorites',
 'folder.png',
 'IdeaProjects',
 'index.php',
 'index.txt',
 'intro.html',
 'Links',
 'Local Settings',
 'Microsoft',
 'miniproject.html',
 'Music',
 'My Documents',
 'NetHood',
 'New folder',
 'New folder (2)',
 'New folder (3)',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{b79e1557-09ea-11f0-b2d1-8811b02610ed}.TM.blf',
 'NTUSER.DAT{b79e1557-09ea-11f0-b2d1-8811b02610ed}.TM.blf.cnpf',
 'NTUSER.DAT{b79e1557-09ea-11f0-b2d1-8811b02610ed}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{b79e1557-09ea-11f0-b2d1-8811b02610ed}.TMContainer00000000000000000001.regtrans-ms.cnpf',
 'NTUSER.DAT{b79e1557-09ea-11f0-b2d1-8811b02610ed}.TMContainer00000000000000000002.regtrans-ms',
 'NTUSER.DAT{b79e1557-09ea-11f0-b2d1-8811b02610ed}.TMContainer00000000000000000002.regtrans-ms.cnpf',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'postgresql_13.exe',
 'PrintHood',
 'python.py',
 'Recent',
 'Retail_Sales_Profitability_Analysis.ipynb',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled Folder',
 'Untitled.ipynb',
 'untitled.py',
 'Videos']

In [9]:
# reading csv files,r tells Python to treat the \ characters as normal path characters.
df = pd.read_csv(r"C:\Users\avnia\Downloads\superstore.csv", encoding="latin1")

In [10]:
df.head()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,10/13/2010,Low,6,261.5400,0.04,Regular Air,-213.25,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,10/20/2010
1,49,293,10/1/2012,High,49,10123.0200,0.07,Delivery Truck,457.81,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,10/2/2012
2,50,293,10/1/2012,High,27,244.5700,0.01,Regular Air,46.71,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D¨ Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,10/3/2012
3,80,483,7/10/2011,High,30,4965.7595,0.08,Regular Air,1198.97,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,7/12/2011
4,85,515,8/28/2010,Not Specified,19,394.2700,0.08,Regular Air,30.94,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,8/30/2010

In [12]:
df.shape

(8399, 21)

In [13]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Order Priority', 'Order Quantity',
       'Sales', 'Discount', 'Ship Mode', 'Profit', 'Unit Price',
       'Shipping Cost', 'Customer Name', 'Province', 'Region',
       'Customer Segment', 'Product Category', 'Product Sub-Category',
       'Product Name', 'Product Container', 'Product Base Margin',
       'Ship Date'],
      dtype='object')

In [14]:
#gives summary,range index,no. of columns,shows some datasets,dtype,memory use etc 
df.info

<bound method DataFrame.info of       Row ID  Order ID  Order Date Order Priority  Order Quantity       Sales  \
0          1         3  10/13/2010            Low               6    261.5400
1         49       293   10/1/2012           High              49  10123.0200
2         50       293   10/1/2012           High              27    244.5700
3         80       483   7/10/2011           High              30   4965.7595
4         85       515   8/28/2010  Not Specified              19    394.2700
...      ...       ...         ...            ...             ...         ...
8394    7765     55558    8/9/2010         Medium               8   1294.0400
8395    7766     55558    8/9/2010         Medium              23    392.5700
8396    7906     56550    4/8/2011  Not Specified              37    823.7800
8397    7907     56550    4/8/2011  Not Specified               8    469.8375
8398    7914     56581    2/8/2009           High              20   2026.0100

      Discount       Ship Mode   Profit  Unit Price  ...       Customer Name  \
0         0.04     Regular Air  -213.25       38.94  ...  Muhammed MacIntyre
1         0.07  Delivery Truck   457.81      208.16  ...        Barry French
2         0.01     Regular Air    46.71        8.69  ...        Barry French
3         0.08     Regular Air  1198.97      195.99  ...       Clay Rozendal
4         0.08     Regular Air    30.94       21.78  ...      Carlos Soltero
...        ...             ...      ...         ...  ...                 ...
8394      0.05  Delivery Truck  -323.18      150.98  ...          Mick Brown
8395      0.04     Regular Air    22.25       17.07  ...          Mick Brown
8396      0.03     Express Air   343.05       22.23  ...        Frank Hawley
8397      0.00     Regular Air  -159.24       65.99  ...        Frank Hawley
8398      0.10     Express Air   580.43      105.98  ...     Grant Donatelli

     Province   Region Customer Segment Product Category  \
0     Nunavut  Nunavut   Small Business  Office Supplies
1     Nunavut  Nunavut         Consumer  Office Supplies
2     Nunavut  Nunavut         Consumer  Office Supplies
3     Nunavut  Nunavut        Corporate       Technology
4     Nunavut  Nunavut         Consumer  Office Supplies
...       ...      ...              ...              ...
8394  Alberta     West         Consumer        Furniture
8395  Alberta     West         Consumer  Office Supplies
8396  Alberta     West      Home Office        Furniture
8397  Alberta     West      Home Office       Technology
8398  Alberta     West         Consumer        Furniture

                Product Sub-Category  \
0             Storage & Organization
1                         Appliances
2     Binders and Binder Accessories
3       Telephones and Communication
4                         Appliances
...                              ...
8394                       Bookcases
8395                       Envelopes
8396              Office Furnishings
8397    Telephones and Communication
8398              Office Furnishings

                                           Product Name Product Container  \
0      Eldon Base for stackable storage shelf, platinum         Large Box
1     1.7 Cubic Foot Compact "Cube" Office Refrigera...        Jumbo Drum
2      Cardinal Slant-D¨ Ring Binder, Heavy Gauge Vinyl         Small Box
3                                                  R380         Small Box
4                              Holmes HEPA Air Purifier        Medium Box
...                                                 ...               ...
8394                        Bush Mission Pointe Library         Jumbo Box
8395  Recycled Interoffice Envelopes with Re-Use-A-S...         Small Box
8396                          Executive Impressions 14"        Small Pack
8397                                    Talkabout T8367         Small Box
8398  Tenex 46" x 60" Computer Anti-Static Chairmat,...        Medium Box

     Product Base Margin   Ship Date
0                   0.80  10/20/2010
1                   0.58   10/2/2012
2                   0.39   10/3/2012
3                   0.58   7/12/2011
4                   0.50   8/30/2010
...                  ...         ...
8394                0.65    8/9/2010
8395                0.38   8/11/2010
8396                0.41   4/10/2011
8397                0.56    4/9/2011
8398                0.65   2/11/2009

[8399 rows x 21 columns]>

In [15]:
# gives statistical summary
df.describe()

,Row ID,Order ID,Order Quantity,Sales,Discount,Profit,Unit Price,Shipping Cost,Product Base Margin
count,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8336.000000
mean,4200.000000,29965.179783,25.571735,1775.878179,0.049671,181.184424,89.346259,12.838557,0.512513
std,2424.726789,17260.883447,14.481071,3585.050525,0.031823,1196.653371,290.354383,17.264052,0.135589
min,1.000000,3.000000,1.000000,2.240000,0.000000,-14140.700000,0.990000,0.490000,0.350000
25%,2100.500000,15011.500000,13.000000,143.195000,0.020000,-83.315000,6.480000,3.300000,0.380000
50%,4200.000000,29857.000000,26.000000,449.420000,0.050000,-1.500000,20.990000,6.070000,0.520000
75%,6299.500000,44596.000000,38.000000,1709.320000,0.080000,162.750000,85.990000,13.990000,0.590000
max,8399.000000,59973.000000,50.000000,89061.050000,0.250000,27220.690000,6783.020000,164.730000,0.850000

In [17]:
# how many missing (empty/NULL) values are present in each column.
df.isnull().sum()

Row ID                   0
Order ID                 0
Order Date               0
Order Priority           0
Order Quantity           0
Sales                    0
Discount                 0
Ship Mode                0
Profit                   0
Unit Price               0
Shipping Cost            0
Customer Name            0
Province                 0
Region                   0
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Name             0
Product Container        0
Product Base Margin     63
Ship Date                0
dtype: int64

In [30]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)
# renaming cloumn
df = df.rename(columns={"order_quantity": "quantity"})

In [35]:
df.isnull().sum().sort_values(ascending=False)

product_base_margin     63
row_id                   0
customer_name            0
product_container        0
product_name             0
product_sub-category     0
product_category         0
customer_segment         0
region                   0
province                 0
shipping_cost            0
order_id                 0
unit_price               0
profit                   0
ship_mode                0
discount                 0
sales                    0
quantity                 0
order_priority           0
order_date               0
ship_date                0
dtype: int64

In [31]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.dtypes

row_id                           int64
order_id                         int64
order_date              datetime64[ns]
order_priority                  object
quantity                         int64
sales                          float64
discount                       float64
ship_mode                       object
profit                         float64
unit_price                     float64
shipping_cost                  float64
customer_name                   object
province                        object
region                          object
customer_segment                object
product_category                object
product_sub-category            object
product_name                    object
product_container               object
product_base_margin            float64
ship_date               datetime64[ns]
dtype: object

In [22]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["ship_date"] = pd.to_datetime(df["ship_date"])

In [33]:
df.dtypes

row_id                           int64
order_id                         int64
order_date              datetime64[ns]
order_priority                  object
quantity                         int64
sales                          float64
discount                       float64
ship_mode                       object
profit                         float64
unit_price                     float64
shipping_cost                  float64
customer_name                   object
province                        object
region                          object
customer_segment                object
product_category                object
product_sub-category            object
product_name                    object
product_container               object
product_base_margin            float64
ship_date               datetime64[ns]
dtype: object

In [25]:
df[["sales", "quantity", "discount", "profit"]].describe()

              sales  order_quantity     discount        profit
count   8399.000000     8399.000000  8399.000000   8399.000000
mean    1775.878179       25.571735     0.049671    181.184424
std     3585.050525       14.481071     0.031823   1196.653371
min        2.240000        1.000000     0.000000 -14140.700000
25%      143.195000       13.000000     0.020000    -83.315000
50%      449.420000       26.000000     0.050000     -1.500000
75%     1709.320000       38.000000     0.080000    162.750000
max    89061.050000       50.000000     0.250000  27220.690000

In [27]:
df["order_quantity"].min()

1

In [36]:
df["discount"].min()

0.0

In [37]:
df["profit"].min()

-14140.7

In [38]:
df["profit"].max()

27220.69

In [39]:
df[["sales", "quantity", "discount", "profit"]] = df[
    ["sales", "quantity", "discount", "profit"]
].apply(pd.to_numeric, errors="coerce")

In [40]:
df.isnull().sum()

row_id                   0
order_id                 0
order_date               0
order_priority           0
quantity                 0
sales                    0
discount                 0
ship_mode                0
profit                   0
unit_price               0
shipping_cost            0
customer_name            0
province                 0
region                   0
customer_segment         0
product_category         0
product_sub-category     0
product_name             0
product_container        0
product_base_margin     63
ship_date                0
dtype: int64

In [41]:
df["region"].unique()

array(['Nunavut', 'Northwest Territories', 'Atlantic', 'Prarie', 'West',
       'Ontario', 'Quebec', 'Yukon'], dtype=object)

In [43]:
df["product_sub-category"].unique()

array(['Storage & Organization', 'Appliances',
       'Binders and Binder Accessories', 'Telephones and Communication',
       'Office Furnishings', 'Paper', 'Rubber Bands',
       'Computer Peripherals', 'Envelopes', 'Bookcases', 'Tables',
       'Labels', 'Pens & Art Supplies', 'Copiers and Fax',
       'Chairs & Chairmats', 'Scissors, Rulers and Trimmers',
       'Office Machines'], dtype=object)

In [44]:
df["customer_segment"].unique()

array(['Small Business', 'Consumer', 'Corporate', 'Home Office'],
      dtype=object)

In [45]:
df["ship_mode"].unique()

array(['Regular Air', 'Delivery Truck', 'Express Air'], dtype=object)

In [46]:
text_columns = df.select_dtypes(include="object").columns

In [47]:
df[text_columns] = df[text_columns].apply(
    lambda x: x.str.strip()
)

In [48]:
df["region"].unique()

array(['Nunavut', 'Northwest Territories', 'Atlantic', 'Prarie', 'West',
       'Ontario', 'Quebec', 'Yukon'], dtype=object)

In [49]:
# Q1.How much Business are we doing???
# Ans: calculate total sales and profit(sales only can't tell whether the business is goign well)
total_sales = df["sales"].sum()
total_profit = df["profit"].sum()

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)

Total Sales: 14915600.824000001
Total Profit: 1521767.98

In [50]:
#calculate profit 
profit_margin = (total_profit / total_sales) * 100

print("Profit Margin:", profit_margin)

Profit Margin: 10.20252551644714

In [52]:
# Q2.Which product category brings in the most sales, and which actually makes the most money? (sort by total profit)
category_analysis = df.groupby("product_sub-category").agg(
    total_sales=("sales", "sum"),
    total_profit=("profit", "sum")
).sort_values("total_profit", ascending=False)

category_analysis

                                total_sales  total_profit
product_sub-category
Telephones and Communication    1889313.802     316951.62
Office Machines                 2168697.140     307712.93
Binders and Binder Accessories  1022957.590     307413.39
Copiers and Fax                 1130361.300     167361.49
Chairs & Chairmats              1761836.550     149649.73
Office Furnishings               698093.810     100427.93
Appliances                       736991.540      97158.06
Computer Peripherals             795875.940      94287.48
Envelopes                        174085.800      48182.60
Paper                            446452.860      45263.20
Labels                            38981.550      13677.17
Pens & Art Supplies              167107.220       7564.78
Storage & Organization          1070182.600       6664.15
Rubber Bands                      15006.630       -102.67
Scissors, Rulers and Trimmers     80996.310      -7799.25
Bookcases                        822652.040     -33582.13
Tables                          1896008.142     -99062.50

In [59]:
# Calculate profit margin by category
category_analysis["profit_margin"] = (
    category_analysis["total_profit"]
    / category_analysis["total_sales"]
) * 100
category_analysis

                                total_sales  total_profit  profit_margin
product_sub-category
Telephones and Communication    1889313.802     316951.62      16.776018
Office Machines                 2168697.140     307712.93      14.188838
Binders and Binder Accessories  1022957.590     307413.39      30.051431
Copiers and Fax                 1130361.300     167361.49      14.806017
Chairs & Chairmats              1761836.550     149649.73       8.493962
Office Furnishings               698093.810     100427.93      14.386022
Appliances                       736991.540      97158.06      13.183063
Computer Peripherals             795875.940      94287.48      11.847007
Envelopes                        174085.800      48182.60      27.677502
Paper                            446452.860      45263.20      10.138405
Labels                            38981.550      13677.17      35.086265
Pens & Art Supplies              167107.220       7564.78       4.526902
Storage & Organization          1070182.600       6664.15       0.622711
Rubber Bands                      15006.630       -102.67      -0.684164
Scissors, Rulers and Trimmers     80996.310      -7799.25      -9.629142
Bookcases                        822652.040     -33582.13      -4.082179
Tables                          1896008.142     -99062.50      -5.224793

In [61]:
# Now we have:category | total_sales | total_profit | profit_margin

In [62]:
# Region analysis
region_analysis = df.groupby("region").agg(
    total_sales=("sales", "sum"),
    total_profit=("profit", "sum")
).sort_values("total_profit", ascending=False)

region_analysis

                        total_sales  total_profit
region
Ontario                3.063212e+06     346868.54
Prarie                 2.837305e+06     321160.12
West                   3.597549e+06     297008.61
Atlantic               2.014248e+06     238960.66
Quebec                 1.510195e+06     140426.65
Northwest Territories  8.008473e+05     100653.08
Yukon                  9.758674e+05      73849.21
Nunavut                1.163765e+05       2841.11

In [63]:
region_analysis["profit_margin"] = (
    region_analysis["total_profit"]
    / region_analysis["total_sales"]
) * 100

region_analysis

                        total_sales  total_profit  profit_margin
region
Ontario                3.063212e+06     346868.54      11.323685
Prarie                 2.837305e+06     321160.12      11.319198
West                   3.597549e+06     297008.61       8.255859
Atlantic               2.014248e+06     238960.66      11.863516
Quebec                 1.510195e+06     140426.65       9.298577
Northwest Territories  8.008473e+05     100653.08      12.568323
Yukon                  9.758674e+05      73849.21       7.567546
Nunavut                1.163765e+05       2841.11       2.441309

In [66]:
loss_making = df[df["profit"] < 0]
len(loss_making)

4264

In [67]:
loss_making["profit"].sum()

np.float64(-1102503.01)

In [69]:
loss_making.sort_values(
    "profit"
).head()

,row_id,order_id,order_date,order_priority,quantity,sales,discount,ship_mode,profit,unit_price,...,customer_name,province,region,customer_segment,product_category,product_sub-category,product_name,product_container,product_base_margin,ship_date
8313,5213,37095,2009-03-10,Low,3,18888.00,0.09,Regular Air,-14140.70,6783.02,...,Roy Phan,Alberta,West,Consumer,Technology,Office Machines,Polycom ViewStationª ISDN Videoconferencing Unit,Large Box,0.39,2009-03-14
7677,6076,43044,2009-10-17,Medium,3,19707.20,0.04,Regular Air,-12558.00,6783.02,...,Laurel Workman,Alberta,West,Home Office,Technology,Office Machines,Polycom ViewStationª ISDN Videoconferencing Unit,Large Box,0.39,2009-10-19
7968,7223,51553,2011-11-27,Not Specified,3,21366.51,0.00,Regular Air,-11984.40,6783.02,...,Adrian Barton,Alberta,West,Small Business,Technology,Office Machines,Polycom ViewStationª ISDN Videoconferencing Unit,Large Box,0.39,2011-11-28
5913,6086,43110,2011-02-06,High,1,3457.99,0.05,Regular Air,-11861.46,3499.99,...,Maxwell Schwartz,Saskachewan,Prarie,Corporate,Technology,Copiers and Fax,Canon imageCLASS 2200 Advanced Copier,Large Box,0.37,2011-02-08
4661,3198,22917,2009-03-01,Medium,1,3550.28,0.06,Express Air,-11769.17,3499.99,...,Nathan Mautz,New Brunswick,Atlantic,Corporate,Technology,Copiers and Fax,Canon imageCLASS 2200 Advanced Copier,Large Box,0.37,2009-03-04

In [70]:
loss_making.sort_values(
    "profit"
).tail()

,row_id,order_id,order_date,order_priority,quantity,sales,discount,ship_mode,profit,unit_price,...,customer_name,province,region,customer_segment,product_category,product_sub-category,product_name,product_container,product_base_margin,ship_date
1882,3433,24486,2011-04-22,Medium,14,27.06,0.00,Regular Air,-0.06,1.76,...,Pete Armstrong,Ontario,Ontario,Consumer,Office Supplies,Pens & Art Supplies,Newell 310,Wrap Bag,0.56,2011-04-23
53,782,5569,2010-04-29,Not Specified,12,118.97,0.09,Regular Air,-0.06,9.65,...,Frank Price,Nunavut,Nunavut,Corporate,Furniture,Office Furnishings,"Eldon Expressionsª Desk Accessory, Wood Pencil...",Small Box,0.55,2010-05-01
4958,1882,13540,2010-05-23,High,16,34.93,0.04,Regular Air,-0.05,2.18,...,Theresa Swint,Manitoba,Prarie,Consumer,Office Supplies,Rubber Bands,Stockwell Push Pins,Wrap Bag,0.52,2010-05-23
3866,66,386,2011-01-24,High,4,14.96,0.02,Regular Air,-0.03,3.69,...,Tracy Poddar,Ontario,Ontario,Corporate,Office Supplies,Labels,Avery 501,Small Box,0.38,2011-01-26
615,4530,32199,2009-07-15,High,8,46.97,0.03,Regular Air,-0.01,5.84,...,Erica Bern,Prince Edward Island,Atlantic,Corporate,Office Supplies,Pens & Art Supplies,Newell 312,Wrap Bag,0.55,2009-07-17

In [76]:
df.to_csv(
    r"C:\Users\avnia\OneDrive\Documents\Project2\data\superstore_clean.csv",
    index=False
)